apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.6
    path: "/nfsdata/data0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.6
    path: "/nfsdata/data1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.6
    path: "/nfsdata/data2"